### Register a new driver
POST http://localhost:3000/drivers
Content-Type: application/json

{
  "id": "driver123",
  "name": "John Doe"
}

### Request a ride
POST http://localhost:3000/rides
Content-Type: application/json

{
  "rideId": "ride123",
  "riderId": "rider123",
  "pickupLocation": {
    "latitude": 0,
    "longitude": 0
  },
  "dropOfLocation": {
    "latitude": 0.01,
    "longitude": 0
  }
}

### Accept a ride
POST http://localhost:3000/drivers/accept-ride
Content-Type: application/json

{
  "driverId": "driver123",
  "rideId": "ride123"
}

### Start a trip
POST http://localhost:3000/drivers/start-trip
Content-Type: application/json

{
  "driverId": "driver123",
  "rideId": "ride123"
}

### Complete a ride
POST http://localhost:3000/drivers/complete-ride
Content-Type: application/json

{
  "driverId": "driver123",
  "rideId": "ride123",
  "fareAmount": 50
}
